flongo:
  restart: always
  build: ./flongo
  expose:
    - "5000"
  volumes:
    - .:/flongo
  links:
    - mongo:mongo
  env_file: .env
  command: /usr/local/bin/gunicorn -w 4 -b :5000 flongo:app
mongo:
  image: mongo:3.3.10
nginx:
  restart: always
  build: ./nginx
  ports:
    - "80:80"
  expose:
    - "80"
  volumes_from:
    - flongo
  links:
    - flongo:flongo
