flongo:
  restart: always
  build: ./flongo
  command: python -u runserver.py
  expose:
    - "5000"
  volumes:
    - .:/flongo
  links:
    - mongo:mongo
mongo:
  image: mongo:3.3.10
nginx:
  restart: always
  build: ./nginx
  expose:
    - "80"
  ports:
    - "80:80"
  volumes_from:
    - flongo
  links:
    - flongo:flongo
